server:
  servlet:
    context-path: /api/v1
  port: 8085


logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(%-40.40logger{39}){cyan}
      %clr(:){faint} %m%n%wEx'
  level:
    root: info
    org.hibernate: warn
    org.hibernate.SQL: warn
    org.hibernate.type.descriptor.sql: warn
    org.springframework.security: warn

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
    username: ${USER}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

#http://localhost:8085/api/v1/swagger-ui/index.html
