server:
  servlet:
    context-path: /api/v1

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(%-40.40logger{39}){cyan}
      %clr(:){faint} %m%n%wEx'

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

spring:
  liquibase:
    change-log: classpath:liquibase-donfundy.xml
  datasource:
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
    username: ${USER}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
